### ISSUE TITLE
Findings while experimenting with the library

### ISSUE THREAD

**Issue by bali182** [JasonStorey/Optional.js#10]
So related to #7 I cloned the repo and started experimenting with it. Found a few things that are a bit strange in terms of javascript:

1. `Supplier` - In java the `Supplier` interface simply expresses the need for a `() -> T` function which is materialized in a `get` function since there are no first-class functions in the language. In js terms it simply doesn't make sense to expect a `get` function on the given value, or even to include this as a possibility. I kinda think that you wanted to allow `Optional`s as suppliers, but that just includes more confusion, when that `get` throws on an absent `Optional`...
2. Exceptions - Throwing errors with the message `NullPointerException - ...` also doesn't make too much sense in js terms, and are more confusing than helpful. I'd use either an `Error` subclass (like `NullPointerError`) or simply describe the problem in the error message, like `"Expected stable value, got null/undefined"`

Let me know what you think!

**Comment by JasonStorey** [comment]
Hi @bali182 - thanks for your comments.

1. I think I originally just wanted to follow the Java 8 API as close as possible - you're right though, this makes no sense. I guess we could allow both? Test for a `.get`, if not call the supplier. Probably confusing and less performant though. It's a change to the API anyway, so might be best to just bump a major and scrap the `.get` nonsense.

2. I think I was just being cute. The error messages still do have a reasonable description in them, but they could definitely be more helpful.

**Comment by JasonStorey** [comment]
Both of these things have been addressed since https://github.com/JasonStorey/Optional.js/commit/c1b5662b0b09e00113375e6fead4ba8dae09cd01.

Thanks for you comments, @bali182

Closing.
