### ISSUE TITLE
Update lib to implement Java 9 API (Optional::ifPresentOrElse and Optional::or)

### ISSUE THREAD

**Issue by fieldju** [JasonStorey/Optional.js#14]
Java 9 has added 2 new methods, `ifPresentOrElse` and `or`

```java
Optional<Object> foo = someMethodThatReturnsOptional();
foo.ifPresentOrElse(
   (fooActual) -> { doSomethingWithFoo(fooActual) },
   () -> { doSomethingElseBecauseFooNotPresent() }
);
```

```java
Optional<Object> foo = Optional.ofNullable(getBarFromNewDb(id)).Or(getBarFromLegacyDb(id));
```

I would love these 2 new methods, I could dig through the source and make a PR if that is a thing you would be interested in.

Cheers,

Justin

**Comment by JasonStorey** [comment]
Excellent. Thanks for the PR!

Merged. I'll get a release out with this in.

**Comment by fieldju** [comment]
https://github.com/JasonStorey/Optional.js/pull/15 merged.
