### ISSUE TITLE
Support for Optional.of(Promise)

### ISSUE THREAD

**Issue by whirlwin** [JasonStorey/Optional.js#6]
Hi!

As you probably have guessed I'm avid user of optional-js - thanks for making it! :+1: I'm working on [try-js](https://github.com/whirlwin/try-js) which is similar in many ways, and I will soon add support for ES2015 promises.

I was wondering if this is something that would be useful in optional-js as well.

E.g.

```javascript
var examplePromise = new Promise((resolve, reject) => {
    resolve(10);
});

Optional.ofNullable(examplePromise)
    .map(value => value + 10)
    .ifPresent(value => console.log(value)); // 20
```

What do you think? Yay or nay?

**Comment by JasonStorey** [comment]
Interesting.

So with an async promise, is the wrapping optional empty until the promise has been either resolved or rejected?

And if the promise is resolved or rejected with no value, I'm guessing the wrapping optional is empty?

**Comment by whirlwin** [comment]
Yes, @JasonStorey, you are correct. I'm not sure what to do with functions like `isPresent()` though. Returning the promise may seem a blit strange, but maybe it's the most correct thing way of implementing it?

**Comment by bali182** [comment]
Wouldn't the extensions on the `Promise` class provided by `bluebird` be a better candidate for this? If you are coming from scala (which seems to be the case considering the try-js lib) this functionality is also not on `Option`s, rather on a separate `Future` class. This would mix concerns a bit too much I think.

**Comment by JasonStorey** [comment]
I think @bali182 's comments seem sensible here, so I'm going to close for now.

@whirlwin Please re-open if have more thoughts on this, though.
